// usage/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import '../../../my-element.js';

@Component({
  selector: 'app-root',
  template: `
    <my-element
      [audienceProp]="audience"
      [attr.frameWork-attr]="framework"
      (customEvent)="handleEvent($event)"
      ></my-element>
  `
})
export class AppComponent {
  audience = { audience: 'world' };
  framework = 'angular';

  handleEvent(evt: CustomEvent) {
    alert('Hello' + evt.detail);
  }
}

// usage/vue/src/App.vue
<template>
  <div id="app">
    <my-element 
      :audienceProp.prop="audience"
      :framework-attr="framework"
      @customEvent="handleEvent($event)"
      ></my-element>
  </div>
</template>

<script>
import './my-element.js';

export default {
  name: 'app',
  data() {
    return {
      audience: { audience: 'world' },
      framework: 'Vue'
    }
  },
  methods: {
    handleEvent(evt) {
      alert('Hello' + evt.detail);
    }
  }
}
</script>
