// usage/react-wc/src/App.js
import React from 'react';
import './my-element.js';

function App() {

  const handleEvent = evt => {
      alert('Hello' + evt.detail);
  }

  const framework = 'React';
  const audience = { audience: 'World' };

  return (
    <div className="App">
      <my-element 
        audienceProp={audience}
        framework-attr={framework}
        onCustomEvent={handleEvent}
      ></my-element>
    </div>
  );
}

export default App;

// usage/vue/src/App.vue
<template>
  <div id="app">
    <my-element 
      :audienceProp.prop="audience"
      :framework-attr="framework"
      @customEvent="handleEvent($event)"
      ></my-element>
  </div>
</template>

<script>
import './my-element.js';

export default {
  name: 'app',
  data() {
    return {
      audience: { audience: 'world' },
      framework: 'Vue'
    }
  },
  methods: {
    handleEvent(evt) {
      alert('Hello' + evt.detail);
    }
  }
}
</script>
